// Copyright 2020 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/simple_op_store.proto

package simple_op_storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteRefState int32

const (
	RemoteRefState_New     RemoteRefState = 0
	RemoteRefState_Tracked RemoteRefState = 1
)

// Enum value maps for RemoteRefState.
var (
	RemoteRefState_name = map[int32]string{
		0: "New",
		1: "Tracked",
	}
	RemoteRefState_value = map[string]int32{
		"New":     0,
		"Tracked": 1,
	}
)

func (x RemoteRefState) Enum() *RemoteRefState {
	p := new(RemoteRefState)
	*p = x
	return p
}

func (x RemoteRefState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteRefState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_simple_op_store_proto_enumTypes[0].Descriptor()
}

func (RemoteRefState) Type() protoreflect.EnumType {
	return &file_proto_simple_op_store_proto_enumTypes[0]
}

func (x RemoteRefState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteRefState.Descriptor instead.
func (RemoteRefState) EnumDescriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{0}
}

type RefConflictLegacy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	Removes [][]byte `protobuf:"bytes,1,rep,name=removes,proto3" json:"removes,omitempty"`
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	Adds          [][]byte `protobuf:"bytes,2,rep,name=adds,proto3" json:"adds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefConflictLegacy) Reset() {
	*x = RefConflictLegacy{}
	mi := &file_proto_simple_op_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefConflictLegacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefConflictLegacy) ProtoMessage() {}

func (x *RefConflictLegacy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefConflictLegacy.ProtoReflect.Descriptor instead.
func (*RefConflictLegacy) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *RefConflictLegacy) GetRemoves() [][]byte {
	if x != nil {
		return x.Removes
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *RefConflictLegacy) GetAdds() [][]byte {
	if x != nil {
		return x.Adds
	}
	return nil
}

// This is redundant with `RefTargetTerm`. It exists for historical reasons.
// TODO: Consider deprecating it.
type RefConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removes       []*RefConflict_Term    `protobuf:"bytes,1,rep,name=removes,proto3" json:"removes,omitempty"`
	Adds          []*RefConflict_Term    `protobuf:"bytes,2,rep,name=adds,proto3" json:"adds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefConflict) Reset() {
	*x = RefConflict{}
	mi := &file_proto_simple_op_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefConflict) ProtoMessage() {}

func (x *RefConflict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefConflict.ProtoReflect.Descriptor instead.
func (*RefConflict) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{1}
}

func (x *RefConflict) GetRemoves() []*RefConflict_Term {
	if x != nil {
		return x.Removes
	}
	return nil
}

func (x *RefConflict) GetAdds() []*RefConflict_Term {
	if x != nil {
		return x.Adds
	}
	return nil
}

// RefTarget that may be serialized in legacy form.
type RefTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New `RefConflict` type represents both `commit_id` and `conflict_legacy`.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*RefTarget_CommitId
	//	*RefTarget_ConflictLegacy
	//	*RefTarget_Conflict
	Value         isRefTarget_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefTarget) Reset() {
	*x = RefTarget{}
	mi := &file_proto_simple_op_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefTarget) ProtoMessage() {}

func (x *RefTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefTarget.ProtoReflect.Descriptor instead.
func (*RefTarget) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{2}
}

func (x *RefTarget) GetValue() isRefTarget_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *RefTarget) GetCommitId() []byte {
	if x != nil {
		if x, ok := x.Value.(*RefTarget_CommitId); ok {
			return x.CommitId
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *RefTarget) GetConflictLegacy() *RefConflictLegacy {
	if x != nil {
		if x, ok := x.Value.(*RefTarget_ConflictLegacy); ok {
			return x.ConflictLegacy
		}
	}
	return nil
}

func (x *RefTarget) GetConflict() *RefConflict {
	if x != nil {
		if x, ok := x.Value.(*RefTarget_Conflict); ok {
			return x.Conflict
		}
	}
	return nil
}

type isRefTarget_Value interface {
	isRefTarget_Value()
}

type RefTarget_CommitId struct {
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	CommitId []byte `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3,oneof"`
}

type RefTarget_ConflictLegacy struct {
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	ConflictLegacy *RefConflictLegacy `protobuf:"bytes,2,opt,name=conflict_legacy,json=conflictLegacy,proto3,oneof"`
}

type RefTarget_Conflict struct {
	Conflict *RefConflict `protobuf:"bytes,3,opt,name=conflict,proto3,oneof"`
}

func (*RefTarget_CommitId) isRefTarget_Value() {}

func (*RefTarget_ConflictLegacy) isRefTarget_Value() {}

func (*RefTarget_Conflict) isRefTarget_Value() {}

// RefTarget term that should be serialized in native form, in which positive
// and negative terms alternate.
type RefTargetTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefTargetTerm) Reset() {
	*x = RefTargetTerm{}
	mi := &file_proto_simple_op_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefTargetTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefTargetTerm) ProtoMessage() {}

func (x *RefTargetTerm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefTargetTerm.ProtoReflect.Descriptor instead.
func (*RefTargetTerm) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{3}
}

func (x *RefTargetTerm) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RemoteBookmark struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RemoteName string                 `protobuf:"bytes,1,opt,name=remote_name,json=remoteName,proto3" json:"remote_name,omitempty"`
	Target     *RefTarget             `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Introduced in jj 0.11.
	State         *RemoteRefState `protobuf:"varint,3,opt,name=state,proto3,enum=simple_op_store.RemoteRefState,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteBookmark) Reset() {
	*x = RemoteBookmark{}
	mi := &file_proto_simple_op_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteBookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteBookmark) ProtoMessage() {}

func (x *RemoteBookmark) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteBookmark.ProtoReflect.Descriptor instead.
func (*RemoteBookmark) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{4}
}

func (x *RemoteBookmark) GetRemoteName() string {
	if x != nil {
		return x.RemoteName
	}
	return ""
}

func (x *RemoteBookmark) GetTarget() *RefTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RemoteBookmark) GetState() RemoteRefState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return RemoteRefState_New
}

type Bookmark struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Unset if the bookmark has been deleted locally.
	LocalTarget *RefTarget `protobuf:"bytes,2,opt,name=local_target,json=localTarget,proto3" json:"local_target,omitempty"`
	// Deprecated since jj 0.34.
	//
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	RemoteBookmarks []*RemoteBookmark `protobuf:"bytes,3,rep,name=remote_bookmarks,json=remoteBookmarks,proto3" json:"remote_bookmarks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bookmark) Reset() {
	*x = Bookmark{}
	mi := &file_proto_simple_op_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookmark) ProtoMessage() {}

func (x *Bookmark) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookmark.ProtoReflect.Descriptor instead.
func (*Bookmark) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{5}
}

func (x *Bookmark) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bookmark) GetLocalTarget() *RefTarget {
	if x != nil {
		return x.LocalTarget
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *Bookmark) GetRemoteBookmarks() []*RemoteBookmark {
	if x != nil {
		return x.RemoteBookmarks
	}
	return nil
}

type GitRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This field is just for historical reasons (before we had the RefTarget
	// type). New GitRefs have (only) the target field.
	// TODO: Delete support for the old format.
	//
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	CommitId      []byte     `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Target        *RefTarget `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRef) Reset() {
	*x = GitRef{}
	mi := &file_proto_simple_op_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRef) ProtoMessage() {}

func (x *GitRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRef.ProtoReflect.Descriptor instead.
func (*GitRef) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{6}
}

func (x *GitRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *GitRef) GetCommitId() []byte {
	if x != nil {
		return x.CommitId
	}
	return nil
}

func (x *GitRef) GetTarget() *RefTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type RemoteRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetTerms   []*RefTargetTerm       `protobuf:"bytes,2,rep,name=target_terms,json=targetTerms,proto3" json:"target_terms,omitempty"`
	State         RemoteRefState         `protobuf:"varint,3,opt,name=state,proto3,enum=simple_op_store.RemoteRefState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteRef) Reset() {
	*x = RemoteRef{}
	mi := &file_proto_simple_op_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRef) ProtoMessage() {}

func (x *RemoteRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRef.ProtoReflect.Descriptor instead.
func (*RemoteRef) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteRef) GetTargetTerms() []*RefTargetTerm {
	if x != nil {
		return x.TargetTerms
	}
	return nil
}

func (x *RemoteRef) GetState() RemoteRefState {
	if x != nil {
		return x.State
	}
	return RemoteRefState_New
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        *RefTarget             `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_simple_op_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{8}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetTarget() *RefTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type View struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HeadIds [][]byte               `protobuf:"bytes,1,rep,name=head_ids,json=headIds,proto3" json:"head_ids,omitempty"`
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	WcCommitId  []byte            `protobuf:"bytes,2,opt,name=wc_commit_id,json=wcCommitId,proto3" json:"wc_commit_id,omitempty"`
	WcCommitIds map[string][]byte `protobuf:"bytes,8,rep,name=wc_commit_ids,json=wcCommitIds,proto3" json:"wc_commit_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Local bookmarks and remote bookmarks in legacy form.
	Bookmarks []*Bookmark `protobuf:"bytes,5,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
	LocalTags []*Tag      `protobuf:"bytes,6,rep,name=local_tags,json=localTags,proto3" json:"local_tags,omitempty"`
	// Introduced in jj 0.34.
	RemoteViews []*RemoteView `protobuf:"bytes,11,rep,name=remote_views,json=remoteViews,proto3" json:"remote_views,omitempty"`
	// Only a subset of the refs. For example, does not include refs/notes/.
	GitRefs []*GitRef `protobuf:"bytes,3,rep,name=git_refs,json=gitRefs,proto3" json:"git_refs,omitempty"`
	// This field is just for historical reasons (before we had the RefTarget
	// type). New Views have (only) the target field.
	// TODO: Delete support for the old format.
	//
	// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
	GitHeadLegacy []byte     `protobuf:"bytes,7,opt,name=git_head_legacy,json=gitHeadLegacy,proto3" json:"git_head_legacy,omitempty"`
	GitHead       *RefTarget `protobuf:"bytes,9,opt,name=git_head,json=gitHead,proto3" json:"git_head,omitempty"`
	// Whether "@git" tags have been migrated to remote_views.
	HasGitRefsMigratedToRemoteTags bool `protobuf:"varint,12,opt,name=has_git_refs_migrated_to_remote_tags,json=hasGitRefsMigratedToRemoteTags,proto3" json:"has_git_refs_migrated_to_remote_tags,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_proto_simple_op_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{9}
}

func (x *View) GetHeadIds() [][]byte {
	if x != nil {
		return x.HeadIds
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *View) GetWcCommitId() []byte {
	if x != nil {
		return x.WcCommitId
	}
	return nil
}

func (x *View) GetWcCommitIds() map[string][]byte {
	if x != nil {
		return x.WcCommitIds
	}
	return nil
}

func (x *View) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

func (x *View) GetLocalTags() []*Tag {
	if x != nil {
		return x.LocalTags
	}
	return nil
}

func (x *View) GetRemoteViews() []*RemoteView {
	if x != nil {
		return x.RemoteViews
	}
	return nil
}

func (x *View) GetGitRefs() []*GitRef {
	if x != nil {
		return x.GitRefs
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/simple_op_store.proto.
func (x *View) GetGitHeadLegacy() []byte {
	if x != nil {
		return x.GitHeadLegacy
	}
	return nil
}

func (x *View) GetGitHead() *RefTarget {
	if x != nil {
		return x.GitHead
	}
	return nil
}

func (x *View) GetHasGitRefsMigratedToRemoteTags() bool {
	if x != nil {
		return x.HasGitRefsMigratedToRemoteTags
	}
	return false
}

type RemoteView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bookmarks     []*RemoteRef           `protobuf:"bytes,2,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
	Tags          []*RemoteRef           `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteView) Reset() {
	*x = RemoteView{}
	mi := &file_proto_simple_op_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteView) ProtoMessage() {}

func (x *RemoteView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteView.ProtoReflect.Descriptor instead.
func (*RemoteView) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteView) GetBookmarks() []*RemoteRef {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

func (x *RemoteView) GetTags() []*RemoteRef {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Operation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ViewId   []byte                 `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	Parents  [][]byte               `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Metadata *OperationMetadata     `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Introduced in jj 0.30.
	CommitPredecessors []*CommitPredecessors `protobuf:"bytes,4,rep,name=commit_predecessors,json=commitPredecessors,proto3" json:"commit_predecessors,omitempty"`
	// Whether or not `commit_predecessors` is recorded.
	StoresCommitPredecessors bool `protobuf:"varint,5,opt,name=stores_commit_predecessors,json=storesCommitPredecessors,proto3" json:"stores_commit_predecessors,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_simple_op_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{11}
}

func (x *Operation) GetViewId() []byte {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *Operation) GetParents() [][]byte {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Operation) GetMetadata() *OperationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Operation) GetCommitPredecessors() []*CommitPredecessors {
	if x != nil {
		return x.CommitPredecessors
	}
	return nil
}

func (x *Operation) GetStoresCommitPredecessors() bool {
	if x != nil {
		return x.StoresCommitPredecessors
	}
	return false
}

// TODO: Share with store.proto? Do we even need the timezone here?
type Timestamp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MillisSinceEpoch int64                  `protobuf:"varint,1,opt,name=millis_since_epoch,json=millisSinceEpoch,proto3" json:"millis_since_epoch,omitempty"`
	TzOffset         int32                  `protobuf:"varint,2,opt,name=tz_offset,json=tzOffset,proto3" json:"tz_offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_proto_simple_op_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{12}
}

func (x *Timestamp) GetMillisSinceEpoch() int64 {
	if x != nil {
		return x.MillisSinceEpoch
	}
	return 0
}

func (x *Timestamp) GetTzOffset() int32 {
	if x != nil {
		return x.TzOffset
	}
	return 0
}

type OperationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *Timestamp             `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *Timestamp             `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	IsSnapshot    bool                   `protobuf:"varint,7,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
	WorkspaceName *string                `protobuf:"bytes,8,opt,name=workspace_name,json=workspaceName,proto3,oneof" json:"workspace_name,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationMetadata) Reset() {
	*x = OperationMetadata{}
	mi := &file_proto_simple_op_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationMetadata) ProtoMessage() {}

func (x *OperationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationMetadata.ProtoReflect.Descriptor instead.
func (*OperationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{13}
}

func (x *OperationMetadata) GetStartTime() *Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *OperationMetadata) GetEndTime() *Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *OperationMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperationMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *OperationMetadata) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OperationMetadata) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

func (x *OperationMetadata) GetWorkspaceName() string {
	if x != nil && x.WorkspaceName != nil {
		return *x.WorkspaceName
	}
	return ""
}

func (x *OperationMetadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CommitPredecessors struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommitId       []byte                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	PredecessorIds [][]byte               `protobuf:"bytes,2,rep,name=predecessor_ids,json=predecessorIds,proto3" json:"predecessor_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitPredecessors) Reset() {
	*x = CommitPredecessors{}
	mi := &file_proto_simple_op_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPredecessors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPredecessors) ProtoMessage() {}

func (x *CommitPredecessors) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPredecessors.ProtoReflect.Descriptor instead.
func (*CommitPredecessors) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{14}
}

func (x *CommitPredecessors) GetCommitId() []byte {
	if x != nil {
		return x.CommitId
	}
	return nil
}

func (x *CommitPredecessors) GetPredecessorIds() [][]byte {
	if x != nil {
		return x.PredecessorIds
	}
	return nil
}

type RefConflict_Term struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefConflict_Term) Reset() {
	*x = RefConflict_Term{}
	mi := &file_proto_simple_op_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefConflict_Term) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefConflict_Term) ProtoMessage() {}

func (x *RefConflict_Term) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_op_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefConflict_Term.ProtoReflect.Descriptor instead.
func (*RefConflict_Term) Descriptor() ([]byte, []int) {
	return file_proto_simple_op_store_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RefConflict_Term) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_simple_op_store_proto protoreflect.FileDescriptor

const file_proto_simple_op_store_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/simple_op_store.proto\x12\x0fsimple_op_store\"I\n" +
	"\x11RefConflictLegacy\x12\x1c\n" +
	"\aremoves\x18\x01 \x03(\fB\x02\x18\x01R\aremoves\x12\x16\n" +
	"\x04adds\x18\x02 \x03(\fB\x02\x18\x01R\x04adds\"\xae\x01\n" +
	"\vRefConflict\x12;\n" +
	"\aremoves\x18\x01 \x03(\v2!.simple_op_store.RefConflict.TermR\aremoves\x125\n" +
	"\x04adds\x18\x02 \x03(\v2!.simple_op_store.RefConflict.TermR\x04adds\x1a+\n" +
	"\x04Term\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xc6\x01\n" +
	"\tRefTarget\x12!\n" +
	"\tcommit_id\x18\x01 \x01(\fB\x02\x18\x01H\x00R\bcommitId\x12Q\n" +
	"\x0fconflict_legacy\x18\x02 \x01(\v2\".simple_op_store.RefConflictLegacyB\x02\x18\x01H\x00R\x0econflictLegacy\x12:\n" +
	"\bconflict\x18\x03 \x01(\v2\x1c.simple_op_store.RefConflictH\x00R\bconflictB\a\n" +
	"\x05value\"4\n" +
	"\rRefTargetTerm\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xab\x01\n" +
	"\x0eRemoteBookmark\x12\x1f\n" +
	"\vremote_name\x18\x01 \x01(\tR\n" +
	"remoteName\x122\n" +
	"\x06target\x18\x02 \x01(\v2\x1a.simple_op_store.RefTargetR\x06target\x12:\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1f.simple_op_store.RemoteRefStateH\x00R\x05state\x88\x01\x01B\b\n" +
	"\x06_state\"\xad\x01\n" +
	"\bBookmark\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\flocal_target\x18\x02 \x01(\v2\x1a.simple_op_store.RefTargetR\vlocalTarget\x12N\n" +
	"\x10remote_bookmarks\x18\x03 \x03(\v2\x1f.simple_op_store.RemoteBookmarkB\x02\x18\x01R\x0fremoteBookmarks\"q\n" +
	"\x06GitRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\tcommit_id\x18\x02 \x01(\fB\x02\x18\x01R\bcommitId\x122\n" +
	"\x06target\x18\x03 \x01(\v2\x1a.simple_op_store.RefTargetR\x06target\"\x99\x01\n" +
	"\tRemoteRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\ftarget_terms\x18\x02 \x03(\v2\x1e.simple_op_store.RefTargetTermR\vtargetTerms\x125\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1f.simple_op_store.RemoteRefStateR\x05state\"M\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06target\x18\x02 \x01(\v2\x1a.simple_op_store.RefTargetR\x06target\"\xf2\x04\n" +
	"\x04View\x12\x19\n" +
	"\bhead_ids\x18\x01 \x03(\fR\aheadIds\x12$\n" +
	"\fwc_commit_id\x18\x02 \x01(\fB\x02\x18\x01R\n" +
	"wcCommitId\x12J\n" +
	"\rwc_commit_ids\x18\b \x03(\v2&.simple_op_store.View.WcCommitIdsEntryR\vwcCommitIds\x127\n" +
	"\tbookmarks\x18\x05 \x03(\v2\x19.simple_op_store.BookmarkR\tbookmarks\x123\n" +
	"\n" +
	"local_tags\x18\x06 \x03(\v2\x14.simple_op_store.TagR\tlocalTags\x12>\n" +
	"\fremote_views\x18\v \x03(\v2\x1b.simple_op_store.RemoteViewR\vremoteViews\x122\n" +
	"\bgit_refs\x18\x03 \x03(\v2\x17.simple_op_store.GitRefR\agitRefs\x12*\n" +
	"\x0fgit_head_legacy\x18\a \x01(\fB\x02\x18\x01R\rgitHeadLegacy\x125\n" +
	"\bgit_head\x18\t \x01(\v2\x1a.simple_op_store.RefTargetR\agitHead\x12L\n" +
	"$has_git_refs_migrated_to_remote_tags\x18\f \x01(\bR\x1ehasGitRefsMigratedToRemoteTags\x1a>\n" +
	"\x10WcCommitIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01J\x04\b\x04\x10\x05J\x04\b\n" +
	"\x10\v\"\x8a\x01\n" +
	"\n" +
	"RemoteView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\tbookmarks\x18\x02 \x03(\v2\x1a.simple_op_store.RemoteRefR\tbookmarks\x12.\n" +
	"\x04tags\x18\x03 \x03(\v2\x1a.simple_op_store.RemoteRefR\x04tags\"\x92\x02\n" +
	"\tOperation\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\fR\x06viewId\x12\x18\n" +
	"\aparents\x18\x02 \x03(\fR\aparents\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\".simple_op_store.OperationMetadataR\bmetadata\x12T\n" +
	"\x13commit_predecessors\x18\x04 \x03(\v2#.simple_op_store.CommitPredecessorsR\x12commitPredecessors\x12<\n" +
	"\x1astores_commit_predecessors\x18\x05 \x01(\bR\x18storesCommitPredecessors\"V\n" +
	"\tTimestamp\x12,\n" +
	"\x12millis_since_epoch\x18\x01 \x01(\x03R\x10millisSinceEpoch\x12\x1b\n" +
	"\ttz_offset\x18\x02 \x01(\x05R\btzOffset\"\xd2\x03\n" +
	"\x11OperationMetadata\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.simple_op_store.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.simple_op_store.TimestampR\aendTime\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1f\n" +
	"\vis_snapshot\x18\a \x01(\bR\n" +
	"isSnapshot\x12*\n" +
	"\x0eworkspace_name\x18\b \x01(\tH\x00R\rworkspaceName\x88\x01\x01\x12R\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v22.simple_op_store.OperationMetadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_workspace_name\"Z\n" +
	"\x12CommitPredecessors\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\fR\bcommitId\x12'\n" +
	"\x0fpredecessor_ids\x18\x02 \x03(\fR\x0epredecessorIds*&\n" +
	"\x0eRemoteRefState\x12\a\n" +
	"\x03New\x10\x00\x12\v\n" +
	"\aTracked\x10\x01BDZBgithub.com/rselbach/jj-git-prompt/internal/jj/pb/simple_op_storepbb\x06proto3"

var (
	file_proto_simple_op_store_proto_rawDescOnce sync.Once
	file_proto_simple_op_store_proto_rawDescData []byte
)

func file_proto_simple_op_store_proto_rawDescGZIP() []byte {
	file_proto_simple_op_store_proto_rawDescOnce.Do(func() {
		file_proto_simple_op_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_op_store_proto_rawDesc), len(file_proto_simple_op_store_proto_rawDesc)))
	})
	return file_proto_simple_op_store_proto_rawDescData
}

var file_proto_simple_op_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_simple_op_store_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_simple_op_store_proto_goTypes = []any{
	(RemoteRefState)(0),        // 0: simple_op_store.RemoteRefState
	(*RefConflictLegacy)(nil),  // 1: simple_op_store.RefConflictLegacy
	(*RefConflict)(nil),        // 2: simple_op_store.RefConflict
	(*RefTarget)(nil),          // 3: simple_op_store.RefTarget
	(*RefTargetTerm)(nil),      // 4: simple_op_store.RefTargetTerm
	(*RemoteBookmark)(nil),     // 5: simple_op_store.RemoteBookmark
	(*Bookmark)(nil),           // 6: simple_op_store.Bookmark
	(*GitRef)(nil),             // 7: simple_op_store.GitRef
	(*RemoteRef)(nil),          // 8: simple_op_store.RemoteRef
	(*Tag)(nil),                // 9: simple_op_store.Tag
	(*View)(nil),               // 10: simple_op_store.View
	(*RemoteView)(nil),         // 11: simple_op_store.RemoteView
	(*Operation)(nil),          // 12: simple_op_store.Operation
	(*Timestamp)(nil),          // 13: simple_op_store.Timestamp
	(*OperationMetadata)(nil),  // 14: simple_op_store.OperationMetadata
	(*CommitPredecessors)(nil), // 15: simple_op_store.CommitPredecessors
	(*RefConflict_Term)(nil),   // 16: simple_op_store.RefConflict.Term
	nil,                        // 17: simple_op_store.View.WcCommitIdsEntry
	nil,                        // 18: simple_op_store.OperationMetadata.AttributesEntry
}
var file_proto_simple_op_store_proto_depIdxs = []int32{
	16, // 0: simple_op_store.RefConflict.removes:type_name -> simple_op_store.RefConflict.Term
	16, // 1: simple_op_store.RefConflict.adds:type_name -> simple_op_store.RefConflict.Term
	1,  // 2: simple_op_store.RefTarget.conflict_legacy:type_name -> simple_op_store.RefConflictLegacy
	2,  // 3: simple_op_store.RefTarget.conflict:type_name -> simple_op_store.RefConflict
	3,  // 4: simple_op_store.RemoteBookmark.target:type_name -> simple_op_store.RefTarget
	0,  // 5: simple_op_store.RemoteBookmark.state:type_name -> simple_op_store.RemoteRefState
	3,  // 6: simple_op_store.Bookmark.local_target:type_name -> simple_op_store.RefTarget
	5,  // 7: simple_op_store.Bookmark.remote_bookmarks:type_name -> simple_op_store.RemoteBookmark
	3,  // 8: simple_op_store.GitRef.target:type_name -> simple_op_store.RefTarget
	4,  // 9: simple_op_store.RemoteRef.target_terms:type_name -> simple_op_store.RefTargetTerm
	0,  // 10: simple_op_store.RemoteRef.state:type_name -> simple_op_store.RemoteRefState
	3,  // 11: simple_op_store.Tag.target:type_name -> simple_op_store.RefTarget
	17, // 12: simple_op_store.View.wc_commit_ids:type_name -> simple_op_store.View.WcCommitIdsEntry
	6,  // 13: simple_op_store.View.bookmarks:type_name -> simple_op_store.Bookmark
	9,  // 14: simple_op_store.View.local_tags:type_name -> simple_op_store.Tag
	11, // 15: simple_op_store.View.remote_views:type_name -> simple_op_store.RemoteView
	7,  // 16: simple_op_store.View.git_refs:type_name -> simple_op_store.GitRef
	3,  // 17: simple_op_store.View.git_head:type_name -> simple_op_store.RefTarget
	8,  // 18: simple_op_store.RemoteView.bookmarks:type_name -> simple_op_store.RemoteRef
	8,  // 19: simple_op_store.RemoteView.tags:type_name -> simple_op_store.RemoteRef
	14, // 20: simple_op_store.Operation.metadata:type_name -> simple_op_store.OperationMetadata
	15, // 21: simple_op_store.Operation.commit_predecessors:type_name -> simple_op_store.CommitPredecessors
	13, // 22: simple_op_store.OperationMetadata.start_time:type_name -> simple_op_store.Timestamp
	13, // 23: simple_op_store.OperationMetadata.end_time:type_name -> simple_op_store.Timestamp
	18, // 24: simple_op_store.OperationMetadata.attributes:type_name -> simple_op_store.OperationMetadata.AttributesEntry
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_simple_op_store_proto_init() }
func file_proto_simple_op_store_proto_init() {
	if File_proto_simple_op_store_proto != nil {
		return
	}
	file_proto_simple_op_store_proto_msgTypes[2].OneofWrappers = []any{
		(*RefTarget_CommitId)(nil),
		(*RefTarget_ConflictLegacy)(nil),
		(*RefTarget_Conflict)(nil),
	}
	file_proto_simple_op_store_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_simple_op_store_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_simple_op_store_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_simple_op_store_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_op_store_proto_rawDesc), len(file_proto_simple_op_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_op_store_proto_goTypes,
		DependencyIndexes: file_proto_simple_op_store_proto_depIdxs,
		EnumInfos:         file_proto_simple_op_store_proto_enumTypes,
		MessageInfos:      file_proto_simple_op_store_proto_msgTypes,
	}.Build()
	File_proto_simple_op_store_proto = out.File
	file_proto_simple_op_store_proto_goTypes = nil
	file_proto_simple_op_store_proto_depIdxs = nil
}
