// Copyright 2025 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/default_index.proto

package default_indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control file to link operation to index segments.
type SegmentControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash (or file name) of the commit index segment.
	CommitSegmentId []byte `protobuf:"bytes,1,opt,name=commit_segment_id,json=commitSegmentId,proto3" json:"commit_segment_id,omitempty"`
	// First commit stored in the changed-path index segments. Unset if
	// changed-path index is disabled.
	ChangedPathStartCommitPos *uint32 `protobuf:"varint,2,opt,name=changed_path_start_commit_pos,json=changedPathStartCommitPos,proto3,oneof" json:"changed_path_start_commit_pos,omitempty"`
	// Hashes (or file names) of the changed-path index segments.
	ChangedPathSegmentIds [][]byte `protobuf:"bytes,3,rep,name=changed_path_segment_ids,json=changedPathSegmentIds,proto3" json:"changed_path_segment_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SegmentControl) Reset() {
	*x = SegmentControl{}
	mi := &file_proto_default_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentControl) ProtoMessage() {}

func (x *SegmentControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_default_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentControl.ProtoReflect.Descriptor instead.
func (*SegmentControl) Descriptor() ([]byte, []int) {
	return file_proto_default_index_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentControl) GetCommitSegmentId() []byte {
	if x != nil {
		return x.CommitSegmentId
	}
	return nil
}

func (x *SegmentControl) GetChangedPathStartCommitPos() uint32 {
	if x != nil && x.ChangedPathStartCommitPos != nil {
		return *x.ChangedPathStartCommitPos
	}
	return 0
}

func (x *SegmentControl) GetChangedPathSegmentIds() [][]byte {
	if x != nil {
		return x.ChangedPathSegmentIds
	}
	return nil
}

var File_proto_default_index_proto protoreflect.FileDescriptor

const file_proto_default_index_proto_rawDesc = "" +
	"\n" +
	"\x19proto/default_index.proto\x12\rdefault_index\"\xde\x01\n" +
	"\x0eSegmentControl\x12*\n" +
	"\x11commit_segment_id\x18\x01 \x01(\fR\x0fcommitSegmentId\x12E\n" +
	"\x1dchanged_path_start_commit_pos\x18\x02 \x01(\rH\x00R\x19changedPathStartCommitPos\x88\x01\x01\x127\n" +
	"\x18changed_path_segment_ids\x18\x03 \x03(\fR\x15changedPathSegmentIdsB \n" +
	"\x1e_changed_path_start_commit_posBBZ@github.com/rselbach/jj-git-prompt/internal/jj/pb/default_indexpbb\x06proto3"

var (
	file_proto_default_index_proto_rawDescOnce sync.Once
	file_proto_default_index_proto_rawDescData []byte
)

func file_proto_default_index_proto_rawDescGZIP() []byte {
	file_proto_default_index_proto_rawDescOnce.Do(func() {
		file_proto_default_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_default_index_proto_rawDesc), len(file_proto_default_index_proto_rawDesc)))
	})
	return file_proto_default_index_proto_rawDescData
}

var file_proto_default_index_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_default_index_proto_goTypes = []any{
	(*SegmentControl)(nil), // 0: default_index.SegmentControl
}
var file_proto_default_index_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_default_index_proto_init() }
func file_proto_default_index_proto_init() {
	if File_proto_default_index_proto != nil {
		return
	}
	file_proto_default_index_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_default_index_proto_rawDesc), len(file_proto_default_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_default_index_proto_goTypes,
		DependencyIndexes: file_proto_default_index_proto_depIdxs,
		MessageInfos:      file_proto_default_index_proto_msgTypes,
	}.Build()
	File_proto_default_index_proto = out.File
	file_proto_default_index_proto_goTypes = nil
	file_proto_default_index_proto_depIdxs = nil
}
