// Copyright 2020 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/local_working_copy.proto

package local_working_copypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_Normal     FileType = 0
	FileType_Symlink    FileType = 1
	FileType_Executable FileType = 2
	// Deprecated: Marked as deprecated in proto/local_working_copy.proto.
	FileType_Conflict     FileType = 3
	FileType_GitSubmodule FileType = 4
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "Normal",
		1: "Symlink",
		2: "Executable",
		3: "Conflict",
		4: "GitSubmodule",
	}
	FileType_value = map[string]int32{
		"Normal":       0,
		"Symlink":      1,
		"Executable":   2,
		"Conflict":     3,
		"GitSubmodule": 4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_local_working_copy_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_proto_local_working_copy_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{0}
}

type MaterializedConflictData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: maybe we should store num_sides here as well
	ConflictMarkerLen uint32 `protobuf:"varint,1,opt,name=conflict_marker_len,json=conflictMarkerLen,proto3" json:"conflict_marker_len,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaterializedConflictData) Reset() {
	*x = MaterializedConflictData{}
	mi := &file_proto_local_working_copy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedConflictData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedConflictData) ProtoMessage() {}

func (x *MaterializedConflictData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedConflictData.ProtoReflect.Descriptor instead.
func (*MaterializedConflictData) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{0}
}

func (x *MaterializedConflictData) GetConflictMarkerLen() uint32 {
	if x != nil {
		return x.ConflictMarkerLen
	}
	return 0
}

type FileState struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	MtimeMillisSinceEpoch    int64                     `protobuf:"varint,1,opt,name=mtime_millis_since_epoch,json=mtimeMillisSinceEpoch,proto3" json:"mtime_millis_since_epoch,omitempty"`
	Size                     uint64                    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	FileType                 FileType                  `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=local_working_copy.FileType" json:"file_type,omitempty"`
	MaterializedConflictData *MaterializedConflictData `protobuf:"bytes,5,opt,name=materialized_conflict_data,json=materializedConflictData,proto3" json:"materialized_conflict_data,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FileState) Reset() {
	*x = FileState{}
	mi := &file_proto_local_working_copy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileState) ProtoMessage() {}

func (x *FileState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileState.ProtoReflect.Descriptor instead.
func (*FileState) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{1}
}

func (x *FileState) GetMtimeMillisSinceEpoch() int64 {
	if x != nil {
		return x.MtimeMillisSinceEpoch
	}
	return 0
}

func (x *FileState) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileState) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_Normal
}

func (x *FileState) GetMaterializedConflictData() *MaterializedConflictData {
	if x != nil {
		return x.MaterializedConflictData
	}
	return nil
}

type FileStateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State         *FileState             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStateEntry) Reset() {
	*x = FileStateEntry{}
	mi := &file_proto_local_working_copy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStateEntry) ProtoMessage() {}

func (x *FileStateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStateEntry.ProtoReflect.Descriptor instead.
func (*FileStateEntry) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{2}
}

func (x *FileStateEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileStateEntry) GetState() *FileState {
	if x != nil {
		return x.State
	}
	return nil
}

type SparsePatterns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []string               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparsePatterns) Reset() {
	*x = SparsePatterns{}
	mi := &file_proto_local_working_copy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparsePatterns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparsePatterns) ProtoMessage() {}

func (x *SparsePatterns) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparsePatterns.ProtoReflect.Descriptor instead.
func (*SparsePatterns) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{3}
}

func (x *SparsePatterns) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type TreeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in proto/local_working_copy.proto.
	LegacyTreeId []byte `protobuf:"bytes,1,opt,name=legacy_tree_id,json=legacyTreeId,proto3" json:"legacy_tree_id,omitempty"`
	// Alternating positive and negative terms if there's a conflict, otherwise a
	// single (positive) value
	TreeIds [][]byte `protobuf:"bytes,5,rep,name=tree_ids,json=treeIds,proto3" json:"tree_ids,omitempty"`
	// Labels for the terms of a conflict.
	ConflictLabels     []string          `protobuf:"bytes,7,rep,name=conflict_labels,json=conflictLabels,proto3" json:"conflict_labels,omitempty"`
	FileStates         []*FileStateEntry `protobuf:"bytes,2,rep,name=file_states,json=fileStates,proto3" json:"file_states,omitempty"`
	IsFileStatesSorted bool              `protobuf:"varint,6,opt,name=is_file_states_sorted,json=isFileStatesSorted,proto3" json:"is_file_states_sorted,omitempty"`
	SparsePatterns     *SparsePatterns   `protobuf:"bytes,3,opt,name=sparse_patterns,json=sparsePatterns,proto3" json:"sparse_patterns,omitempty"`
	WatchmanClock      *WatchmanClock    `protobuf:"bytes,4,opt,name=watchman_clock,json=watchmanClock,proto3" json:"watchman_clock,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TreeState) Reset() {
	*x = TreeState{}
	mi := &file_proto_local_working_copy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeState) ProtoMessage() {}

func (x *TreeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeState.ProtoReflect.Descriptor instead.
func (*TreeState) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Marked as deprecated in proto/local_working_copy.proto.
func (x *TreeState) GetLegacyTreeId() []byte {
	if x != nil {
		return x.LegacyTreeId
	}
	return nil
}

func (x *TreeState) GetTreeIds() [][]byte {
	if x != nil {
		return x.TreeIds
	}
	return nil
}

func (x *TreeState) GetConflictLabels() []string {
	if x != nil {
		return x.ConflictLabels
	}
	return nil
}

func (x *TreeState) GetFileStates() []*FileStateEntry {
	if x != nil {
		return x.FileStates
	}
	return nil
}

func (x *TreeState) GetIsFileStatesSorted() bool {
	if x != nil {
		return x.IsFileStatesSorted
	}
	return false
}

func (x *TreeState) GetSparsePatterns() *SparsePatterns {
	if x != nil {
		return x.SparsePatterns
	}
	return nil
}

func (x *TreeState) GetWatchmanClock() *WatchmanClock {
	if x != nil {
		return x.WatchmanClock
	}
	return nil
}

type WatchmanClock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to WatchmanClock:
	//
	//	*WatchmanClock_StringClock
	//	*WatchmanClock_UnixTimestamp
	WatchmanClock isWatchmanClock_WatchmanClock `protobuf_oneof:"watchman_clock"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchmanClock) Reset() {
	*x = WatchmanClock{}
	mi := &file_proto_local_working_copy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchmanClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchmanClock) ProtoMessage() {}

func (x *WatchmanClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchmanClock.ProtoReflect.Descriptor instead.
func (*WatchmanClock) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{5}
}

func (x *WatchmanClock) GetWatchmanClock() isWatchmanClock_WatchmanClock {
	if x != nil {
		return x.WatchmanClock
	}
	return nil
}

func (x *WatchmanClock) GetStringClock() string {
	if x != nil {
		if x, ok := x.WatchmanClock.(*WatchmanClock_StringClock); ok {
			return x.StringClock
		}
	}
	return ""
}

func (x *WatchmanClock) GetUnixTimestamp() int64 {
	if x != nil {
		if x, ok := x.WatchmanClock.(*WatchmanClock_UnixTimestamp); ok {
			return x.UnixTimestamp
		}
	}
	return 0
}

type isWatchmanClock_WatchmanClock interface {
	isWatchmanClock_WatchmanClock()
}

type WatchmanClock_StringClock struct {
	StringClock string `protobuf:"bytes,1,opt,name=string_clock,json=stringClock,proto3,oneof"`
}

type WatchmanClock_UnixTimestamp struct {
	UnixTimestamp int64 `protobuf:"varint,2,opt,name=unix_timestamp,json=unixTimestamp,proto3,oneof"`
}

func (*WatchmanClock_StringClock) isWatchmanClock_WatchmanClock() {}

func (*WatchmanClock_UnixTimestamp) isWatchmanClock_WatchmanClock() {}

type Checkout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation at which the working copy was updated.
	OperationId []byte `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// An identifier for this workspace. It is used for looking up the current
	// working-copy commit in the repo view. Currently a human-readable name.
	// TODO: Is it better to make this a UUID and a have map that to a name in
	// config? That way users can rename a workspace.
	WorkspaceName string `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName,proto3" json:"workspace_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	mi := &file_proto_local_working_copy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_local_working_copy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_proto_local_working_copy_proto_rawDescGZIP(), []int{6}
}

func (x *Checkout) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *Checkout) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

var File_proto_local_working_copy_proto protoreflect.FileDescriptor

const file_proto_local_working_copy_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/local_working_copy.proto\x12\x12local_working_copy\"J\n" +
	"\x18MaterializedConflictData\x12.\n" +
	"\x13conflict_marker_len\x18\x01 \x01(\rR\x11conflictMarkerLen\"\x85\x02\n" +
	"\tFileState\x127\n" +
	"\x18mtime_millis_since_epoch\x18\x01 \x01(\x03R\x15mtimeMillisSinceEpoch\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x129\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\x1c.local_working_copy.FileTypeR\bfileType\x12j\n" +
	"\x1amaterialized_conflict_data\x18\x05 \x01(\v2,.local_working_copy.MaterializedConflictDataR\x18materializedConflictDataJ\x04\b\x04\x10\x05\"Y\n" +
	"\x0eFileStateEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x123\n" +
	"\x05state\x18\x02 \x01(\v2\x1d.local_working_copy.FileStateR\x05state\",\n" +
	"\x0eSparsePatterns\x12\x1a\n" +
	"\bprefixes\x18\x01 \x03(\tR\bprefixes\"\x88\x03\n" +
	"\tTreeState\x12(\n" +
	"\x0elegacy_tree_id\x18\x01 \x01(\fB\x02\x18\x01R\flegacyTreeId\x12\x19\n" +
	"\btree_ids\x18\x05 \x03(\fR\atreeIds\x12'\n" +
	"\x0fconflict_labels\x18\a \x03(\tR\x0econflictLabels\x12C\n" +
	"\vfile_states\x18\x02 \x03(\v2\".local_working_copy.FileStateEntryR\n" +
	"fileStates\x121\n" +
	"\x15is_file_states_sorted\x18\x06 \x01(\bR\x12isFileStatesSorted\x12K\n" +
	"\x0fsparse_patterns\x18\x03 \x01(\v2\".local_working_copy.SparsePatternsR\x0esparsePatterns\x12H\n" +
	"\x0ewatchman_clock\x18\x04 \x01(\v2!.local_working_copy.WatchmanClockR\rwatchmanClock\"o\n" +
	"\rWatchmanClock\x12#\n" +
	"\fstring_clock\x18\x01 \x01(\tH\x00R\vstringClock\x12'\n" +
	"\x0eunix_timestamp\x18\x02 \x01(\x03H\x00R\runixTimestampB\x10\n" +
	"\x0ewatchman_clock\"Z\n" +
	"\bCheckout\x12!\n" +
	"\foperation_id\x18\x02 \x01(\fR\voperationId\x12%\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tR\rworkspaceNameJ\x04\b\x01\x10\x02*W\n" +
	"\bFileType\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\v\n" +
	"\aSymlink\x10\x01\x12\x0e\n" +
	"\n" +
	"Executable\x10\x02\x12\x10\n" +
	"\bConflict\x10\x03\x1a\x02\b\x01\x12\x10\n" +
	"\fGitSubmodule\x10\x04BGZEgithub.com/rselbach/jj-git-prompt/internal/jj/pb/local_working_copypbb\x06proto3"

var (
	file_proto_local_working_copy_proto_rawDescOnce sync.Once
	file_proto_local_working_copy_proto_rawDescData []byte
)

func file_proto_local_working_copy_proto_rawDescGZIP() []byte {
	file_proto_local_working_copy_proto_rawDescOnce.Do(func() {
		file_proto_local_working_copy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_local_working_copy_proto_rawDesc), len(file_proto_local_working_copy_proto_rawDesc)))
	})
	return file_proto_local_working_copy_proto_rawDescData
}

var file_proto_local_working_copy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_local_working_copy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_local_working_copy_proto_goTypes = []any{
	(FileType)(0),                    // 0: local_working_copy.FileType
	(*MaterializedConflictData)(nil), // 1: local_working_copy.MaterializedConflictData
	(*FileState)(nil),                // 2: local_working_copy.FileState
	(*FileStateEntry)(nil),           // 3: local_working_copy.FileStateEntry
	(*SparsePatterns)(nil),           // 4: local_working_copy.SparsePatterns
	(*TreeState)(nil),                // 5: local_working_copy.TreeState
	(*WatchmanClock)(nil),            // 6: local_working_copy.WatchmanClock
	(*Checkout)(nil),                 // 7: local_working_copy.Checkout
}
var file_proto_local_working_copy_proto_depIdxs = []int32{
	0, // 0: local_working_copy.FileState.file_type:type_name -> local_working_copy.FileType
	1, // 1: local_working_copy.FileState.materialized_conflict_data:type_name -> local_working_copy.MaterializedConflictData
	2, // 2: local_working_copy.FileStateEntry.state:type_name -> local_working_copy.FileState
	3, // 3: local_working_copy.TreeState.file_states:type_name -> local_working_copy.FileStateEntry
	4, // 4: local_working_copy.TreeState.sparse_patterns:type_name -> local_working_copy.SparsePatterns
	6, // 5: local_working_copy.TreeState.watchman_clock:type_name -> local_working_copy.WatchmanClock
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_local_working_copy_proto_init() }
func file_proto_local_working_copy_proto_init() {
	if File_proto_local_working_copy_proto != nil {
		return
	}
	file_proto_local_working_copy_proto_msgTypes[5].OneofWrappers = []any{
		(*WatchmanClock_StringClock)(nil),
		(*WatchmanClock_UnixTimestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_local_working_copy_proto_rawDesc), len(file_proto_local_working_copy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_local_working_copy_proto_goTypes,
		DependencyIndexes: file_proto_local_working_copy_proto_depIdxs,
		EnumInfos:         file_proto_local_working_copy_proto_enumTypes,
		MessageInfos:      file_proto_local_working_copy_proto_msgTypes,
	}.Build()
	File_proto_local_working_copy_proto = out.File
	file_proto_local_working_copy_proto_goTypes = nil
	file_proto_local_working_copy_proto_depIdxs = nil
}
