// Copyright 2023 The Jujutsu Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/git_store.proto

package git_storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commit struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Predecessors [][]byte               `protobuf:"bytes,2,rep,name=predecessors,proto3" json:"predecessors,omitempty"`
	ChangeId     []byte                 `protobuf:"bytes,4,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	// Alternating positive and negative terms. Set only for conflicts.
	// Resolved trees are stored in the git commit
	RootTree [][]byte `protobuf:"bytes,1,rep,name=root_tree,json=rootTree,proto3" json:"root_tree,omitempty"`
	// TODO(#1624): delete when we assume that all commits use this format
	UsesTreeConflictFormat bool `protobuf:"varint,10,opt,name=uses_tree_conflict_format,json=usesTreeConflictFormat,proto3" json:"uses_tree_conflict_format,omitempty"`
	// Deprecated: Marked as deprecated in proto/git_store.proto.
	IsOpen bool `protobuf:"varint,8,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	// Deprecated: Marked as deprecated in proto/git_store.proto.
	IsPruned      bool `protobuf:"varint,9,opt,name=is_pruned,json=isPruned,proto3" json:"is_pruned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_proto_git_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_git_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_proto_git_store_proto_rawDescGZIP(), []int{0}
}

func (x *Commit) GetPredecessors() [][]byte {
	if x != nil {
		return x.Predecessors
	}
	return nil
}

func (x *Commit) GetChangeId() []byte {
	if x != nil {
		return x.ChangeId
	}
	return nil
}

func (x *Commit) GetRootTree() [][]byte {
	if x != nil {
		return x.RootTree
	}
	return nil
}

func (x *Commit) GetUsesTreeConflictFormat() bool {
	if x != nil {
		return x.UsesTreeConflictFormat
	}
	return false
}

// Deprecated: Marked as deprecated in proto/git_store.proto.
func (x *Commit) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

// Deprecated: Marked as deprecated in proto/git_store.proto.
func (x *Commit) GetIsPruned() bool {
	if x != nil {
		return x.IsPruned
	}
	return false
}

var File_proto_git_store_proto protoreflect.FileDescriptor

const file_proto_git_store_proto_rawDesc = "" +
	"\n" +
	"\x15proto/git_store.proto\x12\tgit_store\"\xdf\x01\n" +
	"\x06Commit\x12\"\n" +
	"\fpredecessors\x18\x02 \x03(\fR\fpredecessors\x12\x1b\n" +
	"\tchange_id\x18\x04 \x01(\fR\bchangeId\x12\x1b\n" +
	"\troot_tree\x18\x01 \x03(\fR\brootTree\x129\n" +
	"\x19uses_tree_conflict_format\x18\n" +
	" \x01(\bR\x16usesTreeConflictFormat\x12\x1b\n" +
	"\ais_open\x18\b \x01(\bB\x02\x18\x01R\x06isOpen\x12\x1f\n" +
	"\tis_pruned\x18\t \x01(\bB\x02\x18\x01R\bisPrunedB>Z<github.com/rselbach/jj-git-prompt/internal/jj/pb/git_storepbb\x06proto3"

var (
	file_proto_git_store_proto_rawDescOnce sync.Once
	file_proto_git_store_proto_rawDescData []byte
)

func file_proto_git_store_proto_rawDescGZIP() []byte {
	file_proto_git_store_proto_rawDescOnce.Do(func() {
		file_proto_git_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_git_store_proto_rawDesc), len(file_proto_git_store_proto_rawDesc)))
	})
	return file_proto_git_store_proto_rawDescData
}

var file_proto_git_store_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_git_store_proto_goTypes = []any{
	(*Commit)(nil), // 0: git_store.Commit
}
var file_proto_git_store_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_git_store_proto_init() }
func file_proto_git_store_proto_init() {
	if File_proto_git_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_git_store_proto_rawDesc), len(file_proto_git_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_git_store_proto_goTypes,
		DependencyIndexes: file_proto_git_store_proto_depIdxs,
		MessageInfos:      file_proto_git_store_proto_msgTypes,
	}.Build()
	File_proto_git_store_proto = out.File
	file_proto_git_store_proto_goTypes = nil
	file_proto_git_store_proto_depIdxs = nil
}
